FROM node:lts-alpine as builder

ARG REACT_APP_BACKEND_IP=test-release-server
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY . ./
RUN yarn build --no-cache --frozen-lockfile

FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]